---
- name: Allowing jenkins run commands as root
  lineinfile:
    path: /etc/sudoers
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
  become: true

- name: Wait untill jenkins apply changes
  wait_for:
    timeout: 10
  delegate_to: localhost

- name: Download git plugin
  jenkins_plugin:
    name: git
    url_username: admin
    url_password: admin
    url: http://localhost:8080

- name: Install python pip
  package:
    name: python-pip
    state: present
    update_cache: yes

- name: Install python lxml
  package:
    name:  python3-lxml
    state: present
    update_cache: yes

- pip:
    name: python-jenkins

- pip:
    name: lxml

- name: Restart jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait untill jenkins resart
  wait_for:
    timeout: 20
  delegate_to: localhost

- jenkins_job:
    config: "{{ lookup('file', 'deploywordpressjob.xml') }}"
    name: deploy_site
    password: admin
    url: http://localhost:8080
    user: admin

- jenkins_job:
    config: "{{ lookup('file', 'dockerupdatejob.xml') }}"
    name: update_containers
    password: admin
    url: http://localhost:8080
    user: admin

- name: Restart jenkins
  service:
    name: jenkins
    state: restarted
