---
- name: Create initialization scripts directory
  file: path=/var/lib/jenkins/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775

- name: Skipping manual jenkins installation
  lineinfile:
    path: /etc/default/jenkins
    regexp: ^JAVA_ARGS=
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
  become: true

- name: Copy groovy script
  command:
    cmd: cp -r /home/mygit/security.groovy /var/lib/jenkins/init.groovy.d
    cmd: cp -r /home/mygit/user.groovy /var/lib/jenkins/init.groovy.d
 
- name: Restart jenkins server
  service:
    name: jenkins
    state: restarted
