---
- name: Create initialization scripts directory
  file: path=/var/lib/jenkins/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775

- name: Skipping manual jenkins installation and allowing ansible jenkins plugin module download plugins
  lineinfile:
    path: /etc/default/jenkins
    regexp: ^JAVA_ARGS=
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false $JAVA_ARGS -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"'
  become: true

- name: Copy groovy script
  command:
    cmd: cp -r /home/mygit/security.groovy /var/lib/jenkins/init.groovy.d
    cmd: cp -r /home/mygit/user.groovy /var/lib/jenkins/init.groovy.d
 
- name: Restart jenkins server
  service:
    name: jenkins
    state: restarted

- name: wait for jenkins service
  wait_for:
    timeout: 10
  delegate_to: localhost

- name: remove used groovy scripts
  command:
    cmd: rm -r /var/lib/jenkins/init.groovy.d        
