---
- name: Install docker
  package:
    name: docker.io
    state: present
    update_cache: yes

- name: Install docker-compose
  package:
    name: docker-compose
    state: present
    update_cache: yes

- name: Download images and run containers for Wordpress
  command:
    chdir: /home/mygit/dockertest
    cmd: sudo docker-compose up -d

