---

     - name: Install groovy
       apt:
         name: groovy
         state: latest
         update_cache: yes

     - name: Install JDK
       apt:
         name: openjdk-8-jdk
         state: latest
         update_cache: yes

     - name: Import Jenkins Key
       apt_key:
         url: https://pkg.jenkins.io/debian/jenkins.io.key
         state: present

     - apt_repository :
         repo: 'deb http://pkg.jenkins.io/debian-stable binary/'

     - name: Install Jenkins
       apt:
         name: jenkins
         state: latest
         update_cache: yes
    
     - name: Remove jenkins master password request
       lineinfile:
         path=/etc/default/jenkins 
         regexp=^JENKINS_JAVA_OPTIONS
         line=JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
       become: true

     - name: Start Jenkins
       systemd:
         name: jenkins
         state: started
         enabled: true

     - git:
         repo: https://github.com/Jcodex/dockertask.git
         dest: /home/mygit
