---

     - name: Install Ansible
       apt: 
         name: ansible
         state: latest
         update_cache: yes

     - name: Install JDK
       apt:
         name: openjdk-8-jdk
         state: latest
         update_cache: yes

     - name: Import Jenkins Key
       apt_key:
         url: https://pkg.jenkins.io/debian/jenkins.io.key
         state: present

     - name: Adding jenkins PUB key
       command:
         cmd: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9B7D32F2D50582E6

     - apt_repository :
         repo: 'deb http://pkg.jenkins.io/debian-stable binary/'

     - name: Install Jenkins
       apt:
         name: jenkins
         state: latest
         update_cache: yes

     - name: Start Jenkins
       systemd:
         name: jenkins
         state: started
         enabled: true

     - git:
         repo: https://github.com/Jcodex/dockertask.git
         dest: /home/mygit
