version: "3.3"
networks:
 mysqlnet:
volumes:
  php:
  mysqld:
  mydata:
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
     - 80:80/tcp
    volumes:
     - /home/wordsite:/home/wordsite
     - php:/var/run/php
    networks:
     - mysqlnet

  php-fpm:
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
     - /home/wordsite:/home/wordsite
     - php:/var/run/php
     - mysqld:/var/run/mysqld
    networks:
     - mysqlnet

  mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - mysqld:/var/run/mysqld
     - mydata:/var/lib/mysql
    ports:
     - 3306:3306/tcp
    networks:
     - mysqlnet
