FROM ubuntu
RUN apt-get update
RUN apt-get install -y php-mysql php-fpm monit
RUN apt-get install -y php-json php-xmlrpc php-curl php-gd php-xml php-mbstring
RUN useradd -ms /bin/bash wordsite
RUN mkdir -p /var/run/php-fpm
RUN mkdir -p /var/run/php
COPY php-fpm.conf /etc/php/7.2/fpm/php-fpm.conf
COPY www.conf /etc/php/7.2/fpm/pool.d/www.conf
COPY php.ini /etc/php/7.2/fpm/php.ini
COPY wordsite.conf /etc/php/7.2/fpm/pool.d/wordsite.conf
ENTRYPOINT ["/usr/sbin/php-fpm7.2", "-F"]
